### ISSUE TITLE
Be consistent in setting x,y points in configuration files.

### ISSUE THREAD

**Issue by rec** [rec/echomesh#328]
Sometimes I have an ordered pair, sometimes separate x and y coordinates.

```
display:
  background: white
  layout: [16, 16]
  padding:
    top: 10
    left: 10
    bottom: 5
    right: 5
  light:
    background: 0x606060
    border:
      color: black
      width: 1
    padding:
      x: 4
      y: 4
    shape: circle
    show_number: false
    number_padding:
      x: 2
      y: 2
    size: [32, 32]
```
