### ISSUE TITLE
allow lists of colors in color names.

### ISSUE THREAD

**Issue by rec** [rec/echomesh#429]
```
pattern:
  -
    type: insert
    offset: 32
    pattern:
      type: spread
      colors: white, red
      steps: 32
  -
    type: insert
    pattern:
      type: spread
      colors: blue, white
      steps: 32
```

We shouldn't need brackets around the colors.
